### ISSUE TITLE
Keyboard handler

### ISSUE THREAD

**Issue by anzz1** [ikt32/GTAVMenuBase#19]
According to the ScriptHookV doc you should use keyboardHandlerRegister instead of GetAsyncKeyState

> You must use keyboard hook instead of GetKeyState/GetAsyncKeyState WIN API funcs,
because it guarantees that all key presses will be handled correctly.

Due to the unfortunate situation Alexander Blade (scripthookv dev) cannot be asked directly why, but I suspect the the reason is this last part of sentence in the [MSDN doc](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getasynckeystate)

> Determines whether a key is up or down at the time the function is called, **and whether the key was pressed after a previous call to GetAsyncKeyState**.

As when using your awesome [GTAVAddonLoader](https://github.com/E66666666/GTAVAddonLoader) mod, it seems that 50/50 of the time when pressing Escape to enter pause menu, it doesn't register on the first try and have to press it twice (just playing normally, addon spawner menu is not open, and it's the only addon besides ScriptHookV itself). 

So if I had to guess, the reason Alexander instructs against using GetAsyncKeyState, is that maybe the GTA engine relies on this "previous call" part which breaks when adding another GetAsyncKeyState to the pipeline.

Then again, I'm less sure about that since that would be indeed very bad, outdated design as any other app running on the system could also taint the value by calling GetAsyncKeyState, and the MSDN doc states clearly that it's not to be relied on. Could the devs do such a mistake? Idk.

**Comment by ikt32** [comment]
TrainerV also breaks due to this.

I image many implementations look at the wrong bit.

**Comment by ikt32** [comment]
And now Manual Transmission is broken.

I remember why I did away with the convoluted callback now.

**Comment by ikt32** [comment]
Actually I'm reverting this. No use to it. People not knowing what the heck GetAsyncKeyState does is not my problem and I'm not breaking existing features because someone can't read the damn Microsoft docs.
